stages:
  - lint
  - build

include:
  - project: Uniface/tools/defaults
    ref: master
    file: .gitlab-ci-defaults.yml

lint:
  stage: lint
  extends: .uxwidgets
  tags:
    - docker-uniface-local
  script:
    # copy pre-installed modules
    - cp -R /app/node_modules node_modules
    # install correct set of modules
    - npm install --no-update --no-fund
    - echo "Lint repository"
    # do not allow warnings
    - npm run lint

build:
  stage: build
  extends: .uxwidgets
  variables:
    CONTAINER_RELEASE_IMAGE_REPO: $CI_REGISTRY/$CI_PROJECT_PATH
  tags:
    - docker-uniface-local
  script:
    # copy pre-installed modules
    - cp -R /app/node_modules node_modules
    # install correct set of modules
    - npm install --no-update --no-fund
    - echo "Build CSS/JS bundles"
    - npm run build:prod
  artifacts:
    paths:
      - dist/
