stages:
  - lint
  - build
  - test

include:
  - project: Uniface/tools/defaults
    ref: master
    file: .gitlab-ci-defaults.yml

lint:
  stage: lint
  extends: .uxwidgets
  tags:
    - docker-uniface-local
  script:
    - echo "Linting repository"
    - npm run lint

build:
  stage: build
  extends: .uxwidgets
  tags:
    - docker-uniface-local
  script:
    - echo "Building CSS/JS bundles"
    - npm run build:prod
  artifacts:
    paths:
      - dist/

test:
  stage: test
  extends: .uxwidgets
  tags:
    - docker-uniface-local
  script:
    - echo "Running tests"
    - npm run test
  artifacts:
    paths:
      - testAutomation/test-results/
    when: always
